install.packages(c('dplyr','purrr','covr','readr','tidyr','webshot','spelling','readxl','data.table','gridtext','ggtext','tidyselect','testthat','rmarkdown','pkgdown','ggplot2','shiny','shinyTree','shinyjs','SobolSequence','writexl','tictoc','pkgload'), repos = 'http://cran.us.r-project.org', type='win.binary')
install.packages('https://github.com/Open-Systems-Pharmacology/rClr/releases/download/v0.9.1/rClr_0.9.1.zip', repos = NULL, type = 'binary')
install.packages('https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/releases/download/v1.4.23/ospsuite.utils_1.4.23.zip', repos = NULL, type = 'binary')
install.packages('https://github.com/Open-Systems-Pharmacology/TLF-Library/releases/download/v1.5.125/tlf_1.5.125.zip', repos = NULL, type = 'binary')
install.packages('https://github.com/Open-Systems-Pharmacology/OSPSuite-R/releases/download/v11.3.520/ospsuite_11.3.520.zip', repos = NULL, type = 'binary')
